### ISSUE TITLE
lang tekst visning

### ISSUE THREAD

**Issue by AllanRavn** [Autowinto/ShellWeb-Client#11]
![Billede 1](https://user-images.githubusercontent.com/76480928/102891082-ed5eea80-445d-11eb-9c5b-5cc04fc2314f.PNG)
Når der står en lang tekst i passwords sår rykker hele password vinduet ned under kundekortet – det ville være rart hvis det blev liggende til venstre for.
a.	Se billede 1

**Comment by Autowinto** [comment]
Problemet er løst for alle tabs pr. 672f2ac5f855eb76f32380bea7ed3c1757859e6b

Tekst i tabeller wrapper nu også ordentligt hvis de bliver enormt lange.
