### ISSUE TITLE
Password dokumentation

### ISSUE THREAD

**Issue by AllanRavn** [Autowinto/ShellWeb-Client#3]
2)	Når man dokumenterer password og trykker Save, så skal man refreshe browseren og trykke passwords for at kunne dokumentere igen, ellers bliver den bare stående på opret password skærmen og der sker ingenting når man trykker ”save”

**Comment by Autowinto** [comment]
Det skulle gerne være løst pr. opdatering af backenden. En relateret fejl som gjorde, at man ikke kunne tilføje flere end et password uden at refreshe siden er også løst pr.  40fedf82e1f9be4bf2f8ffd2c3dfc196f5a98f88
