### ISSUE TITLE
Sortering

### ISSUE THREAD

**Issue by askalbertsen** [Autowinto/ShellWeb-Client#5]
Nyeste tickets skal helst stå først

**Comment by Autowinto** [comment]
Tickets sorteres nu efter nyeste. Jeg holder sagen åben lidt endnu i forbindelse med tilføjelse af fuld sorteringsfunktionalitet i tabellerne.

**Comment by Autowinto** [comment]
Der er implementeret sortering på de relevante tabeller og alle nye tabeller vil for fremtiden have implementeret sortering.
